/**
 * This class file was automatically generated by jASN1 v1.7.1 (http://www.openmuc.org)
 */

package org.openmuc.jasn1.compiler.pkix1explicit88;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import org.openmuc.jasn1.compiler.pkix1implicit88.*;
import org.openmuc.jasn1.compiler.rspdefinitions.*;

public class Time {

	public byte[] code = null;
	public BerUtcTime utcTime = null;
	public BerGeneralizedTime generalTime = null;
	
	public Time() {
	}

	public Time(byte[] code) {
		this.code = code;
	}

	public Time(BerUtcTime utcTime, BerGeneralizedTime generalTime) {
		this.utcTime = utcTime;
		this.generalTime = generalTime;
	}

	public int encode(BerByteArrayOutputStream os) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (generalTime != null) {
			codeLength += generalTime.encode(os, true);
			return codeLength;
		}
		
		if (utcTime != null) {
			codeLength += utcTime.encode(os, true);
			return codeLength;
		}
		
		throw new IOException("Error encoding BerChoice: No item in choice was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(BerUtcTime.tag)) {
			utcTime = new BerUtcTime();
			codeLength += utcTime.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(BerGeneralizedTime.tag)) {
			generalTime = new BerGeneralizedTime();
			codeLength += generalTime.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding BerChoice: Tag matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
		encode(os);
		code = os.getArray();
	}

	public String toString() {
		if (utcTime != null) {
			return "CHOICE{utcTime: " + utcTime + "}";
		}

		if (generalTime != null) {
			return "CHOICE{generalTime: " + generalTime + "}";
		}

		return "unknown";
	}

}

