/**
 * This class file was automatically generated by jASN1 v1.7.1 (http://www.openmuc.org)
 */

package org.openmuc.jasn1.compiler.pedefinitions;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class PINKeyReferenceValue extends BerInteger {

	public PINKeyReferenceValue() {
	}

	public PINKeyReferenceValue(byte[] code) {
		super(code);
	}

	public PINKeyReferenceValue(BigInteger value) {
		super(value);
	}

	public PINKeyReferenceValue(long value) {
		super(value);
	}

}
