/**
 * This class file was automatically generated by jASN1 v1.7.0 (http://www.openmuc.org)
 */

package org.openmuc.jasn1.compiler.pkix1implicit88;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import org.openmuc.jasn1.compiler.pkix1explicit88.*;
import org.openmuc.jasn1.compiler.rspdefinitions.*;

public class BaseCRLNumber extends CRLNumber {

	public BaseCRLNumber() {
	}

	public BaseCRLNumber(byte[] code) {
		super(code);
	}

	public BaseCRLNumber(BigInteger value) {
		super(value);
	}

	public BaseCRLNumber(long value) {
		super(value);
	}

}
