/**
 * This class file was automatically generated by jASN1 v1.7.0 (http://www.openmuc.org)
 */

package org.openmuc.jasn1.compiler.iso8823_presentation;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class UserSessionRequirements extends BerBitString {

	public UserSessionRequirements() {
	}

	public UserSessionRequirements(byte[] code) {
		super(code);
	}

	public UserSessionRequirements(byte[] value, int numBits) {
		super(value, numBits);
	}

}
