/**
 * This class file was automatically generated by jASN1 v1.7.0 (http://www.openmuc.org)
 */

package org.openmuc.jasn1.compiler.tagging_test;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class SequenceOfIndirectTypes {

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private UntaggedInteger untaggedInt = null;
	private ExplicitlyTaggedInteger untaggedInt2 = null;
	private ImplicitlyTaggedInteger untaggedInt3 = null;
	private UntaggedInteger explicitlyTaggedInt = null;
	private ExplicitlyTaggedInteger explicitlyTaggedInt2 = null;
	private ImplicitlyTaggedInteger explicitlyTaggedInt3 = null;
	private UntaggedInteger implicitlyTaggedInt = null;
	private ExplicitlyTaggedInteger implicitlyTaggedInt2 = null;
	private ImplicitlyTaggedInteger implicitlyTaggedInt3 = null;
	private UntaggedChoice untaggedChoice = null;
	private TaggedChoice untaggedChoice2 = null;
	private UntaggedChoice taggedChoice = null;
	private TaggedChoice taggedChoice2 = null;
	private TaggedAny untaggedAny = null;
	private UntaggedAny taggedAny = null;
	private TaggedAny taggedAny2 = null;
	private TaggedAnyNoDecode untaggedAnyNoDecode = null;
	private UntaggedAnyNoDecode taggedAnyNoDecode = null;
	private TaggedAnyNoDecode taggedAnyNoDecode2 = null;
	
	public SequenceOfIndirectTypes() {
	}

	public SequenceOfIndirectTypes(byte[] code) {
		this.code = code;
	}

	public void setUntaggedInt(UntaggedInteger untaggedInt) {
		this.untaggedInt = untaggedInt;
	}

	public UntaggedInteger getUntaggedInt() {
		return untaggedInt;
	}

	public void setUntaggedInt2(ExplicitlyTaggedInteger untaggedInt2) {
		this.untaggedInt2 = untaggedInt2;
	}

	public ExplicitlyTaggedInteger getUntaggedInt2() {
		return untaggedInt2;
	}

	public void setUntaggedInt3(ImplicitlyTaggedInteger untaggedInt3) {
		this.untaggedInt3 = untaggedInt3;
	}

	public ImplicitlyTaggedInteger getUntaggedInt3() {
		return untaggedInt3;
	}

	public void setExplicitlyTaggedInt(UntaggedInteger explicitlyTaggedInt) {
		this.explicitlyTaggedInt = explicitlyTaggedInt;
	}

	public UntaggedInteger getExplicitlyTaggedInt() {
		return explicitlyTaggedInt;
	}

	public void setExplicitlyTaggedInt2(ExplicitlyTaggedInteger explicitlyTaggedInt2) {
		this.explicitlyTaggedInt2 = explicitlyTaggedInt2;
	}

	public ExplicitlyTaggedInteger getExplicitlyTaggedInt2() {
		return explicitlyTaggedInt2;
	}

	public void setExplicitlyTaggedInt3(ImplicitlyTaggedInteger explicitlyTaggedInt3) {
		this.explicitlyTaggedInt3 = explicitlyTaggedInt3;
	}

	public ImplicitlyTaggedInteger getExplicitlyTaggedInt3() {
		return explicitlyTaggedInt3;
	}

	public void setImplicitlyTaggedInt(UntaggedInteger implicitlyTaggedInt) {
		this.implicitlyTaggedInt = implicitlyTaggedInt;
	}

	public UntaggedInteger getImplicitlyTaggedInt() {
		return implicitlyTaggedInt;
	}

	public void setImplicitlyTaggedInt2(ExplicitlyTaggedInteger implicitlyTaggedInt2) {
		this.implicitlyTaggedInt2 = implicitlyTaggedInt2;
	}

	public ExplicitlyTaggedInteger getImplicitlyTaggedInt2() {
		return implicitlyTaggedInt2;
	}

	public void setImplicitlyTaggedInt3(ImplicitlyTaggedInteger implicitlyTaggedInt3) {
		this.implicitlyTaggedInt3 = implicitlyTaggedInt3;
	}

	public ImplicitlyTaggedInteger getImplicitlyTaggedInt3() {
		return implicitlyTaggedInt3;
	}

	public void setUntaggedChoice(UntaggedChoice untaggedChoice) {
		this.untaggedChoice = untaggedChoice;
	}

	public UntaggedChoice getUntaggedChoice() {
		return untaggedChoice;
	}

	public void setUntaggedChoice2(TaggedChoice untaggedChoice2) {
		this.untaggedChoice2 = untaggedChoice2;
	}

	public TaggedChoice getUntaggedChoice2() {
		return untaggedChoice2;
	}

	public void setTaggedChoice(UntaggedChoice taggedChoice) {
		this.taggedChoice = taggedChoice;
	}

	public UntaggedChoice getTaggedChoice() {
		return taggedChoice;
	}

	public void setTaggedChoice2(TaggedChoice taggedChoice2) {
		this.taggedChoice2 = taggedChoice2;
	}

	public TaggedChoice getTaggedChoice2() {
		return taggedChoice2;
	}

	public void setUntaggedAny(TaggedAny untaggedAny) {
		this.untaggedAny = untaggedAny;
	}

	public TaggedAny getUntaggedAny() {
		return untaggedAny;
	}

	public void setTaggedAny(UntaggedAny taggedAny) {
		this.taggedAny = taggedAny;
	}

	public UntaggedAny getTaggedAny() {
		return taggedAny;
	}

	public void setTaggedAny2(TaggedAny taggedAny2) {
		this.taggedAny2 = taggedAny2;
	}

	public TaggedAny getTaggedAny2() {
		return taggedAny2;
	}

	public void setUntaggedAnyNoDecode(TaggedAnyNoDecode untaggedAnyNoDecode) {
		this.untaggedAnyNoDecode = untaggedAnyNoDecode;
	}

	public TaggedAnyNoDecode getUntaggedAnyNoDecode() {
		return untaggedAnyNoDecode;
	}

	public void setTaggedAnyNoDecode(UntaggedAnyNoDecode taggedAnyNoDecode) {
		this.taggedAnyNoDecode = taggedAnyNoDecode;
	}

	public UntaggedAnyNoDecode getTaggedAnyNoDecode() {
		return taggedAnyNoDecode;
	}

	public void setTaggedAnyNoDecode2(TaggedAnyNoDecode taggedAnyNoDecode2) {
		this.taggedAnyNoDecode2 = taggedAnyNoDecode2;
	}

	public TaggedAnyNoDecode getTaggedAnyNoDecode2() {
		return taggedAnyNoDecode2;
	}

	public int encode(BerByteArrayOutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(BerByteArrayOutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		int sublength;

		codeLength += taggedAnyNoDecode2.encode(os, false);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 19
		os.write(0xB3);
		codeLength += 1;
		
		sublength = taggedAnyNoDecode.encode(os);
		codeLength += sublength;
		codeLength += BerLength.encodeLength(os, sublength);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 9
		os.write(0xA9);
		codeLength += 1;
		
		codeLength += untaggedAnyNoDecode.encode(os, true);
		
		codeLength += taggedAny2.encode(os, false);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 18
		os.write(0xB2);
		codeLength += 1;
		
		sublength = taggedAny.encode(os);
		codeLength += sublength;
		codeLength += BerLength.encodeLength(os, sublength);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 8
		os.write(0xA8);
		codeLength += 1;
		
		codeLength += untaggedAny.encode(os, true);
		
		codeLength += taggedChoice2.encode(os, false);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 15
		os.write(0xAF);
		codeLength += 1;
		
		sublength = taggedChoice.encode(os);
		codeLength += sublength;
		codeLength += BerLength.encodeLength(os, sublength);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 5
		os.write(0xA5);
		codeLength += 1;
		
		codeLength += untaggedChoice2.encode(os, true);
		
		codeLength += untaggedChoice.encode(os);
		
		codeLength += implicitlyTaggedInt3.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 23
		os.write(0x97);
		codeLength += 1;
		
		codeLength += implicitlyTaggedInt2.encode(os, false);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 12
		os.write(0xAC);
		codeLength += 1;
		
		codeLength += implicitlyTaggedInt.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 2
		os.write(0x82);
		codeLength += 1;
		
		sublength = explicitlyTaggedInt3.encode(os, true);
		codeLength += sublength;
		codeLength += BerLength.encodeLength(os, sublength);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 21
		os.write(0xB5);
		codeLength += 1;
		
		sublength = explicitlyTaggedInt2.encode(os, true);
		codeLength += sublength;
		codeLength += BerLength.encodeLength(os, sublength);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 11
		os.write(0xAB);
		codeLength += 1;
		
		sublength = explicitlyTaggedInt.encode(os, true);
		codeLength += sublength;
		codeLength += BerLength.encodeLength(os, sublength);
		// write tag: CONTEXT_CLASS, CONSTRUCTED, 1
		os.write(0xA1);
		codeLength += 1;
		
		codeLength += untaggedInt3.encode(os, true);
		
		codeLength += untaggedInt2.encode(os, true);
		
		codeLength += untaggedInt.encode(os, true);
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(UntaggedInteger.tag)) {
			untaggedInt = new UntaggedInteger();
			subCodeLength += untaggedInt.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(ExplicitlyTaggedInteger.tag)) {
			untaggedInt2 = new ExplicitlyTaggedInteger();
			subCodeLength += untaggedInt2.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(ImplicitlyTaggedInteger.tag)) {
			untaggedInt3 = new ImplicitlyTaggedInteger();
			subCodeLength += untaggedInt3.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 1)) {
			subCodeLength += length.decode(is);
			explicitlyTaggedInt = new UntaggedInteger();
			subCodeLength += explicitlyTaggedInt.decode(is, true);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 11)) {
			subCodeLength += length.decode(is);
			explicitlyTaggedInt2 = new ExplicitlyTaggedInteger();
			subCodeLength += explicitlyTaggedInt2.decode(is, true);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 21)) {
			subCodeLength += length.decode(is);
			explicitlyTaggedInt3 = new ImplicitlyTaggedInteger();
			subCodeLength += explicitlyTaggedInt3.decode(is, true);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			implicitlyTaggedInt = new UntaggedInteger();
			subCodeLength += implicitlyTaggedInt.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 12)) {
			implicitlyTaggedInt2 = new ExplicitlyTaggedInteger();
			subCodeLength += implicitlyTaggedInt2.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 23)) {
			implicitlyTaggedInt3 = new ImplicitlyTaggedInteger();
			subCodeLength += implicitlyTaggedInt3.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		untaggedChoice = new UntaggedChoice();
		subCodeLength += untaggedChoice.decode(is, berTag);
		subCodeLength += berTag.decode(is);
		
		if (berTag.equals(TaggedChoice.tag)) {
			untaggedChoice2 = new TaggedChoice();
			subCodeLength += untaggedChoice2.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 5)) {
			subCodeLength += length.decode(is);
			taggedChoice = new UntaggedChoice();
			subCodeLength += taggedChoice.decode(is, null);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 15)) {
			taggedChoice2 = new TaggedChoice();
			subCodeLength += taggedChoice2.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(TaggedAny.tag)) {
			untaggedAny = new TaggedAny();
			subCodeLength += untaggedAny.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 8)) {
			subCodeLength += length.decode(is);
			taggedAny = new UntaggedAny();
			subCodeLength += taggedAny.decode(is, length.val);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 18)) {
			taggedAny2 = new TaggedAny();
			subCodeLength += taggedAny2.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(TaggedAnyNoDecode.tag)) {
			untaggedAnyNoDecode = new TaggedAnyNoDecode();
			subCodeLength += untaggedAnyNoDecode.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 9)) {
			subCodeLength += length.decode(is);
			taggedAnyNoDecode = new UntaggedAnyNoDecode();
			subCodeLength += taggedAnyNoDecode.decode(is, length.val);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 19)) {
			taggedAnyNoDecode2 = new TaggedAnyNoDecode();
			subCodeLength += taggedAnyNoDecode2.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		BerByteArrayOutputStream os = new BerByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder("SEQUENCE{");
		sb.append("untaggedInt: ").append(untaggedInt);
		
		sb.append(", ");
		sb.append("untaggedInt2: ").append(untaggedInt2);
		
		sb.append(", ");
		sb.append("untaggedInt3: ").append(untaggedInt3);
		
		sb.append(", ");
		sb.append("explicitlyTaggedInt: ").append(explicitlyTaggedInt);
		
		sb.append(", ");
		sb.append("explicitlyTaggedInt2: ").append(explicitlyTaggedInt2);
		
		sb.append(", ");
		sb.append("explicitlyTaggedInt3: ").append(explicitlyTaggedInt3);
		
		sb.append(", ");
		sb.append("implicitlyTaggedInt: ").append(implicitlyTaggedInt);
		
		sb.append(", ");
		sb.append("implicitlyTaggedInt2: ").append(implicitlyTaggedInt2);
		
		sb.append(", ");
		sb.append("implicitlyTaggedInt3: ").append(implicitlyTaggedInt3);
		
		sb.append(", ");
		sb.append("untaggedChoice: ").append(untaggedChoice);
		
		sb.append(", ");
		sb.append("untaggedChoice2: ").append(untaggedChoice2);
		
		sb.append(", ");
		sb.append("taggedChoice: ").append(taggedChoice);
		
		sb.append(", ");
		sb.append("taggedChoice2: ").append(taggedChoice2);
		
		sb.append(", ");
		sb.append("untaggedAny: ").append(untaggedAny);
		
		sb.append(", ");
		sb.append("taggedAny: ").append(taggedAny);
		
		sb.append(", ");
		sb.append("taggedAny2: ").append(taggedAny2);
		
		sb.append(", ");
		sb.append("untaggedAnyNoDecode: ").append(untaggedAnyNoDecode);
		
		sb.append(", ");
		sb.append("taggedAnyNoDecode: ").append(taggedAnyNoDecode);
		
		sb.append(", ");
		sb.append("taggedAnyNoDecode2: ").append(taggedAnyNoDecode2);
		
		sb.append("}");
		return sb.toString();
	}

}

